spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081/
          predicates:
            - Path=/customer/**
        - id: stock
          uri: http://localhost:8082/
          predicates:
            - Path=/stock/**
server:
  port: 8080
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
